
services:
  web:
    image: php:8.2-apache
    container_name: detector_web
    ports:
      - "8080:80"
    volumes:
      - ../src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      sh -c "a2enmod rewrite && sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf && apache2-foreground"